on:
  push:
    branches:
      - 'main'

jobs:
  Publish_Nuget:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET 7.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Extract Branch Name
      shell: bash
      run: echo "PACKAGE_VERSION=${GITHUB_REF#refs/heads/release/}" >> $GITHUB_ENV

    - name: Restore Dependencies
      run: dotnet restore PoliceAPI_Client/PoliceAPI_Client.csproj

    - name: Build Dotnet
      run: dotnet build --configuration Release --no-restore PoliceAPI_Client/PoliceAPI_Client.csproj
